[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eynollah"
version = "0.1.0"




dependencies = [
    "ocrd >= 2.23.3",
    "tensorflow == 2.12.1",
    "scikit-learn >= 0.23.2",
    "imutils >= 0.5.3",
    "numpy < 1.24.0",
    "matplotlib",
    "torch == 2.0.1",
    "transformers == 4.30.2",
    "numba == 0.58.1",
]

[project.scripts]
eynollah = "qurator.eynollah.cli:main"
ocrd-eynollah-segment="qurator.eynollah.ocrd_cli:main"


[tool.setuptools.packages.find]
where = ["."]
include = ["qurator"]

[tool.setuptools.package-data]
"*" = ["*.json", '*.yml', '*.xml', '*.xsd']
