version: 2

jobs:

  build-python37:
    machine:
      - image: ubuntu-2004:2023.02.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - model-cache
      - run: make models
      - save_cache:
          key: model-cache
          paths:
            models_eynollah.tar.gz
            models_eynollah
      - run:
          name: "Set Python Version"
          command: pyenv install -s 3.7.16 && pyenv global 3.7.16
      - run: make install
      - run: make smoke-test

  build-python38:
    machine:
      - image: ubuntu-2004:2023.02.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - model-cache
      - run: make models
      - save_cache:
          key: model-cache
          paths:
            models_eynollah.tar.gz
            models_eynollah
      - run:
          name: "Set Python Version"
          command: pyenv install -s 3.8.16 && pyenv global 3.8.16           
      - run: make install
      - run: make smoke-test

workflows:
  version: 2
  build:
    jobs:
      - build-python37
      - build-python38
